### PR TITLE
Fix test suite failing with PHPUnit 10

### PR DESCRIPTION
**Pull request by thinkverse**
Seems @krekas missed some small things when updating to Laravel 10, so this PR fixes the tests failing on PHPUnit 10 due to the `phpunit.xml` using a now deprecated XML configuration schema. Also updated the `.gitignore` file to exclude tracking the new PHPUnit cache directory. Will check the other repositories and submit PRs if necessary. 👍

Can confirm the test suite passes with these fixes (https://github.com/LaravelDaily/Test-Laravel-Routes/pull/2).

### CODE REVIEW

**Comment by krekas** [comment]
@thinkverse good point, missed it.

**Comment by thinkverse** [comment]
Fixes have now been submitted to all repositories. 👍

**Comment by krekas** [comment]
@PovilasKorop ping

**Comment by PovilasKorop** [comment]
@thinkverse wow outstanding job, I can't express how thankful I am for those fixes!

**Comment by thinkverse** [comment]
> I can't express how thankful I am for those fixes!

The pleasure is all mine, for what you do for this community this is the least I can do. 👍

**Pull request merged**
